### ISSUE TITLE
Please upload to pip

### ISSUE THREAD

**Issue by nedoxff** [dunkyl/SlyUWU-Python#1]
The package is currently not available on pip:
![изображение](https://user-images.githubusercontent.com/65343244/167312186-a1d6b7b4-a24d-4cd9-808a-75e6ba792b73.png)

**Comment by dunkyl** [comment]
What is your python version for this pip?

**Comment by dunkyl** [comment]
This library is for Python 3.10

**Comment by nedoxff** [comment]
Sorry, my bad.. PyLauncher was giving me the wrong version 😓
